stages:
  - clear
  - build
  - pre-build
  - test
  
clear_stage:
  stage: clear
  script:
    - docker stack rm open-planner-backend
    - docker system prune -f
    - docker rmi -f $CI_REGISTRY_IMAGE:$CI_COMMIT_BEFORE_SHA	
  only:
    refs:
      - master
  tags:
    - openplanner-web-shell

build-img: &build
  stage: build
  variables:
    GIT_STRATEGY: pull
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA . --no-cache  
  only:
    refs:
      - master
  tags:
    - openplanner-web-shell

build-stack: 
  <<: *build 
  stage: pre-build
  script:
    -  docker stack deploy -c docker-compose.yml open-planner-backend
  when: delayed
  start_in: 1 minute

testando_api: 
  <<: *build
  stage: test
  script:
    -  curl -L http://open-planner-web.duckdns.org

teste_conexao: 
  <<: *build
  stage: test
  script:
    - echo quit | timeout --signal=9 2 telnet open-planner-web.duckdns.org 8083 2>&1 &

     
