stages:
  - pre-build
#  - test-api
 
pre-build-docker-img: &pre-build 
  stage: pre-build
  variables:
    GIT_STRATEGY: pull
  script:
    -  docker stack rm open-planner-backend
    -  docker volume rm -f open-planner-backend_open-planner-db; docker rmi -f open-planner-api
    -  docker stack deploy -c docker-compose.yml open-planner-backend
  only:
    refs:
      - master
  tags:
    - openplanner-web-shell

#testando_api: 
#  <<: *pre-build
#  stage: test-api
#  script:
#    -  curl -L http://linkedjobs.duckdns.org/swagger-ui/
     
