language: java
jdk: oraclejdk11
os:
  - linux
branches:
  only:
    - master
    - develop
sudo: true
addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
      - postgresql-client-10
before_install:
  - sudo -u postgres psql -c "CREATE USER user.auth WITH PASSWORD 'user.pass'"
  - sudo -u postgres psql -c "ALTER ROLE user.auth SUPERUSER"
before_script:
  - psql -c "CREATE DATABASE open-planner;" -U postgres
