version: '3.1'

services:
  open-planner-db:
    container_name: open-planner-db
    image: postgres:10-alpine
    restart: always
    ports:
      - "5432:5432"
    secrets:
      - db_pass_root
    environment:  
      POSTGRES_DB: open-planner
      POSTGRES_USER: user.auth
      POSTGRES_PASSWORD: "/run/secrets/db_pass_root"
    networks: 
      - backend
    volumes:
      - open-planner-db:/var/lib/postgresql/data

  open-planner-api:
    container_name: open-planner-api
    image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    restart: always
    ports:
      - "8083:8080"
    secrets:
      - db_pass_root
      - db_pass_mail
    environment:  
      DB_URL: jdbc:postgresql://open-planner-db:5432/open-planner
      DB_USER: user.auth
      DB_PASSWORD: "/run/secrets/db_pass_root"
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_SENDER: openplanner.ifpb@gmail.com
      MAIL_USERNAME: openplanner.ifpb@gmail.com
      MAIL_PASSWORD: "/run/secrets/db_pass_mail"
      WEB_APP_BASE_URL: http://open-planner-web.duckdns.org
    networks: 
      - backend
    depends_on:
      - open-planner-db

volumes:
  open-planner-db:
networks:
  backend:
secrets:
  db_pass_mail:
    external: true
  db_pass_root:
    external: true