version: '3.1'

services:
  open-planner-db:
    container_name: open-planner-db
    image: postgres:10-alpine
    restart: always
    ports:
      - "5432:5432"
    secrets:
      - file_secret
    networks: 
      - backend
    volumes:
      - open-planner-db:/var/lib/postgresql/data

  open-planner-api:
    container_name: open-planner-api
    build: '.'
    restart: always
    ports:
      - "8083:8080"
    env_file: 
      - db.env
    networks: 
      - backend
    depends_on:
      - open-planner-db

volumes:
  open-planner-db:
      
networks:
  backend:
      
secrets:   
  file_secret:
    file: ~/db.env 
