version: '3'

services:
  open-planner-db:
    container_name: open-planner-db
    image: postgres:10-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: open-planner
      POSTGRES_USER: user.auth
      POSTGRES_PASSWORD: user.pass
    networks: 
      - backend
    volumes:
      - open-planner-db:/var/lib/postgresql/data

  open-planner-api:
    container_name: open-planner-api
    build: '.'
    restart: always
    ports:
      - "8083:8080"
    environment: 
      DB_URL=$DB_PATH
      DB_USER=$DB_USERS
      DB_PASSWORD=$DB_PASS
    networks: 
      - backend
    depends_on:
      - open-planner-db

volumes:
  open-planner-db:
      
networks:
  backend:
      

